server:
  AppVersion: 1.0.0
  Port: :5001
  Mode: Development
  ReadTimeout: 10
  WriteTimeout: 10
  CtxDefaultTimeout: 12
  WeatherApiUrl: https://example.com/weather
  WeatherSecret: 12secret34
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: debug

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: vessels_db
  PostgresqlSslmode: false
  PgDriver: pgx

